### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile on project client-java-api

### ISSUE THREAD

**Issue by lsafina** [kubernetes-client/java#795]
Hi,

Could you please help me with the following issue I got while executing mvn install: 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project client-java-api: Compilation failure: Compilation failure: 
[ERROR] /Projects/kub/java/kubernetes/target/generated-sources/annotations/io/kubernetes/client/fluent/VisitableMap.java:[37,27] name clash: forEach(java.util.function.Consumer<?>) in io.kubernetes.client.fluent.VisitableMap and forEach(java.util.function.Consumer<? super io.kubernetes.client.fluent.Visitable>) in java.lang.Iterable have the same erasure, yet neither overrides the other
[ERROR] /Projects/kub/java/kubernetes/target/generated-sources/annotations/io/kubernetes/client/fluent/VisitableMap.java:[37,5] method does not override or implement a method from a supertype
[ERROR] /Projects/kub/java/kubernetes/target/generated-sources/annotations/io/kubernetes/client/fluent/VisitableMap.java:[38,33] incompatible types: java.util.function.Consumer<capture#1 of ?> cannot be converted to java.util.function.Consumer<? super io.kubernetes.client.fluent.Visitable>
[ERROR] -> [Help 1]
```
Java version: 13, maven 3.6.2

**Comment by brendandburns** [comment]
Hrm,
I will try to reproduce this. It might be a Java 13 thing.

In the meantime, does an `mvn clean` fix the issue?

**Comment by lsafina** [comment]
Yes, `mvn clean` itself returns `BUILD SUCCESS`.

**Comment by brendandburns** [comment]
after a `mvn clean` does `mvn install` work?

**Comment by lsafina** [comment]
No

**Comment by brendandburns** [comment]
Ok, I will try to reproduce this.

**Comment by brendandburns** [comment]
There definitely appear to be compilation problems with Java 13. For now, I would recommend using an earlier JDK (it compiles w/ Java 11 for example)

We'll continue to try to figure out what's going on here.

**Comment by brendandburns** [comment]
@iocanel I'm seeing failures in compiling the generated code w/ Java 13:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project client-java-api: Compilation failure: Compilation failure: 
[ERROR] /home/brendan/src/java/kubernetes/target/generated-sources/annotations/io/kubernetes/client/fluent/BaseFluent.java:[36,49] incompatible types: java.lang.Object cannot be converted to io.kubernetes.client.fluent.Builder<? extends T>
[ERROR] /home/brendan/src/java/kubernetes/target/generated-sources/annotations/io/kubernetes/client/fluent/BaseFluent.java:[47,49] incompatible types: java.lang.Object cannot be converted to io.kubernetes.client.fluent.Builder<? extends T>
```

The generated code looks like:

```java
    public static <T>ArrayList<T> build(List list){
            if (list == null) {
    return null;
}
            ArrayList<T> result = new ArrayList<T>();
            for (Builder<? extends T> builder : list) {
    result.add(builder.build());
}
            return result;
    }
```

I'm not sure why the `List` isn't getting the right templates, but something is definitely confused.

Have you tested sundr.io on java 13?

Thanks!

**Comment by iocanel** [comment]
No I haven't tested sindriio with javs 13. Only tested up to 11. Will do
ASAP.

**Comment by brendandburns** [comment]
Thanks!

**Comment by iocanel** [comment]
@brendanburns: Just tried sundrio with OpenJDK 13.0.1. Other than some issues related to tests, I didn't notice any other kind of issue.

**Comment by iocanel** [comment]
To be more specific, the generated BuildFluent.java seems to be generated as expected.

To further troubleshoot this, I think that it might make sense to try and use the exact same version and flavour of JDK.

In my tests I am using `sdkman` and I am installing `Java.Net`, `GrallVM` and `Amazon` variants of JDK.

I've only witnesed issues once with `OpenJ9`.

What is the exact version you are using?

**Comment by lsafina** [comment]
I'm using oracle jdk with `jenv` with 2 configurations:

```
java version "11.0.5" 2019-10-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.5+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.5+10-LTS, mixed mode)
$JAVA_HOME = /Library/Java/JavaVirtualMachines/jdk-11.0.5.jdk/Contents/Home/
```
```
java version "13" 2019-09-17
Java(TM) SE Runtime Environment (build 13+33)
Java HotSpot(TM) 64-Bit Server VM (build 13+33, mixed mode, sharing)
$JAVA_HOME = /Library/Java/JavaVirtualMachines/jdk-13.jdk/Contents/Home/
```

**Comment by lsafina** [comment]
Allright, I've found my hero:
```
Maven home: /Users/lsafina/.sdkman/candidates/maven/3.6.1
Java version: 10.0.2, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home
```

Still weird why it didn't work for all the previous versions in my environment...

**Comment by iocanel** [comment]
Ok, let me see how it works with these JDKs for me.

**Comment by sec23206** [comment]
I got exactly the same errors described at the top of this thread with OpenJDK 11.0.5 when using the instructions to build the JAR files (mvn package) with this configuration:
```
$ mvn -version
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T11:06:16-04:00)
Maven home: /usr/local/Cellar/maven/3.6.2/libexec
Java version: 11.0.5, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
```

I see references to others successfully building it with this JDK version, but is the recommendation to drop to v10.x?

Note: when using the "mvn install" option, I'm getting this error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project client-java-api: Fatal error compiling: io.sundr.SundrException: No getter found for property: instance on class: io.kubernetes.client.openapi.models.V1ClusterRoleBindingListFluentImpl -> [Help 1]
```

Thanks!

**Comment by sec23206** [comment]
Update: I installed OpenJDK 10 and retried the instructions to create the JAR files ... the original errors listed at the start of this thread no longer occur, but I'm still getting the the error about "No getter found for property":

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project client-java-api: Fatal error compiling: io.sundr.SundrException: No getter found for property: instance on class: io.kubernetes.client.openapi.models.V1ClusterRoleBindingListFluentImpl -> [Help 1]
```
So this error occurs with both OpenJDK v10 and 11.

**Comment by derekdennybrown** [comment]
I get this on a clean install both in MacOS.  First encountered this with Catalina + JDK 13, then wiped my java/, re-cloned and build with JDK 11.  Both failed with the above message.  A subsequent mvn install failed with a different error (io.sundr.SundrException: No getter found for property: instance on class: io.kubernetes.client.openapi.models.V1ClusterRoleBindingListFluentImpl).  

I was also able to reproduce on Linux with a fresh build using openjdk version "12.0.2" 2019-07-16.

On mac-os, mvn clean && mvn -T=1 install fails in a different way:
[ERROR] ../java/kubernetes/src/main/java/io/kubernetes/client/openapi/apis/AdmissionregistrationApi.java:63: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">

**Comment by iocanel** [comment]
FYI, I did some fixes in sundrio to better support flavors of JDK11 and JDK13 also added some circleci configuration so that pull requests are validated against JDK8, JDK11 and JDK13.

I will release later today!

**Comment by Liyeshe** [comment]
sorry,i don't how to resolve it at the end.where is the method to solve it?

**Comment by brendandburns** [comment]
We now have integration tests for Java 8 -> 13 and they are all passing. Closing this issue.

**Comment by adarshans** [comment]
how to resolve comiler failure error only in jeniins not in eclips in eclips maven test will get success but it will show 
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project SkillraryEcommerceProject: Compilation failure: Compilation failure:   why this happens i have installed all the JRE's and JDK,maven ,git all the thngs installed and added to jenkins. a simple project with one line code can run successfully in jenkins but try with the Huge Frame Work Code it will fails the build
